Repository 0xMiden/miden-vm, pull requests merged in 2024-08, with the labels that each got.

#1426 Minor refactoring of assembler API
  assembly/src/assembler/mod.rs
  assembly/src/assembler/module_graph/debug.rs
  assembly/src/assembler/module_graph/mod.rs
  assembly/src/assembler/tests.rs
  assembly/src/library/error.rs
  assembly/src/library/masl.rs
  assembly/src/library/mod.rs
  assembly/src/library/module.rs
  assembly/src/library/namespace.rs
  assembly/src/library/tests.rs
  assembly/src/testing.rs
  assembly/src/tests.rs
  miden/benches/program_compilation.rs
  miden/benches/program_execution.rs
  miden/src/cli/bundle.rs
  miden/src/cli/data.rs
  miden/src/examples/blake3.rs
  miden/src/repl/mod.rs
  miden/src/tools/mod.rs
  miden/tests/integration/flow_control/mod.rs
  stdlib/build.rs
  stdlib/src/lib.rs
  stdlib/tests/crypto/falcon.rs
  stdlib/tests/mem/mod.rs
  test-utils/src/lib.rs
Labels: no changelog

#1437 test: verify fix for #1377
  assembly/src/tests.rs
Labels: tests, no changelog

#1441 feat: expose pretty printing helper for mast nodes
  CHANGELOG.md
  assembly/src/library/mod.rs
  core/src/mast/node/mod.rs
Labels: enhancement

#1461 add basic block merging threshold
  CHANGELOG.md
  assembly/src/assembler/mast_forest_builder.rs
  core/src/mast/node/basic_block_node/mod.rs
  miden/Cargo.toml
  miden/benches/program_compilation.rs
Labels: assembly

#1471 chore: Add warning about `no_std` environment
  README.md
  miden/README.md
  processor/README.md
  prover/README.md
  verifier/README.md
Labels: no changelog
