Repository 0xMiden/miden-vm, pull requests merged in 2024-09, with the labels that each got.

#1481 fix(assembly): properly indent first op in nested blocks
  CHANGELOG.md
  assembly/src/ast/block.rs
Labels: bug, assembly

#1480 feat: improve handling of u32 operations
  CHANGELOG.md
  assembly/src/assembler/instruction/u32_ops.rs
  docs/src/user_docs/assembly/u32_operations.md
  miden/tests/integration/operations/u32_ops/arithmetic_ops.rs
  miden/tests/integration/operations/u32_ops/bitwise_ops.rs
  miden/tests/integration/operations/u32_ops/comparison_ops.rs
  miden/tests/integration/operations/u32_ops/mod.rs
  processor/src/operations/u32_ops.rs
  stdlib/asm/math/u64.masm
  stdlib/tests/math/u64_mod.rs
Labels: enhancement, assembly, processor

#1482 Fix `MastForest` serialization
  assembly/src/assembler/mod.rs
  core/src/mast/mod.rs
  core/src/mast/node/basic_block_node/mod.rs
  core/src/mast/serialization/basic_block_data_builder.rs
  core/src/mast/serialization/basic_block_data_decoder.rs
  core/src/mast/serialization/basic_blocks.rs
  core/src/mast/serialization/decorator.rs
  core/src/mast/serialization/info.rs
  core/src/mast/serialization/mod.rs
  core/src/mast/serialization/string_table.rs
  core/src/mast/serialization/tests.rs
Labels: no changelog

#1492 Simplify `batch_ops()`
  core/src/mast/node/basic_block_node/mod.rs
Labels: no changelog

#1495 Fix operation batch flags constraints
  docs/src/design/decoder/constraints.md
  docs/src/design/decoder/main.md
Labels: documentation, no changelog

#1506 Documentation fixes
  docs/src/user_docs/assembly/flow_control.md
  docs/src/user_docs/assembly/io_operations.md
Labels: no changelog

#1510 feat: implement procedure annotation syntax
  CHANGELOG.md
  assembly/src/ast/attribute/meta.rs
  assembly/src/ast/attribute/meta/expr.rs
  assembly/src/ast/attribute/meta/kv.rs
  assembly/src/ast/attribute/meta/list.rs
  assembly/src/ast/attribute/mod.rs
  assembly/src/ast/attribute/set.rs
  assembly/src/ast/mod.rs
  assembly/src/ast/procedure/mod.rs
  assembly/src/ast/procedure/procedure.rs
  assembly/src/ast/tests.rs
  assembly/src/parser/error.rs
  assembly/src/parser/grammar.lalrpop
  assembly/src/parser/lexer.rs
  assembly/src/parser/token.rs
  assembly/src/tests.rs
Labels: enhancement, assembly
