Repository 0xMiden/miden-vm, pull requests merged in 2025-07, with the labels that each got.

#1937 refactor(core): improvements to source management APIs for LSP integration
  CHANGELOG.md
  Cargo.lock
  assembly-syntax/src/parse.rs
  assembly-syntax/src/parser/mod.rs
  assembly-syntax/src/testing/mod.rs
  core/Cargo.toml
  core/src/debuginfo/location.rs
  core/src/debuginfo/mod.rs
  core/src/debuginfo/selection.rs
  core/src/debuginfo/source_file.rs
  core/src/debuginfo/source_manager.rs
  core/src/mast/serialization/decorator.rs
  core/src/mast/serialization/tests.rs
  core/src/operations/decorators/mod.rs
  miden-vm/tests/integration/exec_iters.rs
  miden-vm/tests/integration/flow_control/mod.rs
  miden-vm/tests/integration/operations/decorators/asmop.rs
  miden-vm/tests/integration/operations/io_ops/env_ops.rs
  processor/src/errors.rs
  processor/src/tests.rs
  test-utils/src/lib.rs
  test-utils/src/test_builders.rs
Labels: tools, debugging

#1954 Use crate dependency in core for serialization types
  core/src/mast/mod.rs
  core/src/mast/serialization/basic_blocks.rs
  core/src/mast/serialization/decorator.rs
  core/src/mast/serialization/info.rs
  core/src/mast/serialization/mod.rs
  core/src/mast/serialization/string_table.rs
  core/src/mast/tests.rs
  core/src/operations/mod.rs
  core/src/program.rs
Labels: no changelog

#1956 Helpful error for CLI tests
  miden-vm/tests/integration/cli/cli_test.rs
Labels: no changelog

#1959 Unify `QuadFelt`
  air/src/lib.rs
  core/src/lib.rs
  miden-vm/tests/integration/operations/ext2_ops.rs
  processor/src/chiplets/ace/mod.rs
  processor/src/chiplets/ace/tests/circuit.rs
  processor/src/chiplets/ace/tests/encoder.rs
  processor/src/chiplets/ace/tests/mod.rs
  processor/src/chiplets/ace/trace.rs
  processor/src/errors.rs
  processor/src/fast/circuit_eval.rs
  processor/src/fast/fri_ops.rs
  processor/src/fast/horner_ops.rs
  processor/src/lib.rs
  processor/src/operations/ext2_ops.rs
  processor/src/operations/fri_ops.rs
  processor/src/operations/horner_ops.rs
  processor/src/operations/sys_ops/sys_event_handlers.rs
  stdlib/tests/crypto/arithmetic_circuit_eval.rs
  stdlib/tests/crypto/fri/verifier_fri_e2f4.rs
  stdlib/tests/crypto/stark/mod.rs
  stdlib/tests/crypto/stark/verifier_recursive/channel.rs
  stdlib/tests/crypto/stark/verifier_recursive/mod.rs
  test-utils/src/lib.rs
Labels: no changelog

#2038 Shorten arithmetic_circuit_eval to circuit_eval
  assembly-syntax/src/ast/instruction/mod.rs
  assembly-syntax/src/ast/instruction/print.rs
  assembly-syntax/src/ast/visit.rs
  assembly-syntax/src/parser/grammar.lalrpop
  assembly-syntax/src/parser/token.rs
  assembly/src/instruction/mod.rs
  core/src/mast/serialization/tests.rs
  core/src/operations/mod.rs
  processor/src/chiplets/aux_trace/bus/mod.rs
  processor/src/fast/circuit_eval.rs
  processor/src/fast/mod.rs
  processor/src/fast/tests/all_ops.rs
  processor/src/operations/circuit_eval.rs
  processor/src/operations/mod.rs
  stdlib/asm/crypto/stark/public_inputs.masm
  stdlib/asm/crypto/stark/utils.masm
  stdlib/tests/crypto/circuit_evaluation.rs
  stdlib/tests/crypto/mod.rs
Labels: no changelog

#2034 Add docs for `arithmetic_circuit_eval` op
  docs/src/assets/design/stack/crypto_ops/EVALCIRCUIT.png
  docs/src/design/stack/crypto_ops.md
  docs/src/user_docs/assembly/cryptographic_operations.md
  processor/src/fast/circuit_eval.rs
  processor/src/operations/circuit_eval.rs
Labels: no changelog

#2041 chore: update EXPORTED.md
  docs/src/EXPORTED.md
Labels: documentation, no changelog
