Repository 0xMiden/miden-vm, pull requests merged in 2025-09, with the labels that each got.

#2149 chore(core): use MIN_STACK_DEPTH for StackOutputs Deref target
  core/src/stack/outputs.rs
Labels: no changelog

#2153 update cycle counts for word::gt and word::lte
  stdlib/asm/word.masm
Labels: no changelog

#2156 fix: CI checks stdlib doc is rebuilt and changes checked in
  .github/workflows/test.yml
  stdlib/docs/word.md
Labels: no changelog

#2177 test: un-ignore math::u64_mod::unchecked_shl
  stdlib/tests/math/u64_mod.rs
Labels: no changelog

#2175 ci: workflows follow least privilege
  .github/workflows/bench.yml
  .github/workflows/build.yml
  .github/workflows/changelog.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: no changelog

#2180 chore(docs): Update AdviceProvider docstring
  processor/src/host/advice/mod.rs
Labels: documentation, no changelog

#2176 doc: address various documentation issues
  .github/workflows/link-checker.yml
  CHANGELOG.md
  docs/src/intro/main.md
  docs/src/intro/overview.md
  docs/src/tools/main.md
  lychee.toml
Labels: no changelog

#2184 fix: advice_map loading in test framework for the fast processor
  processor/src/fast/mod.rs
  processor/src/tests.rs
Labels: no changelog

#2173 Attempt to move stack in stack buffer when reaching boundaries
  CHANGELOG.md
  processor/src/fast/basic_block.rs
  processor/src/fast/call_and_dyn.rs
  processor/src/fast/mod.rs
  processor/src/fast/operation.rs
  processor/src/fast/tests/mod.rs
  processor/src/processor/mod.rs
  processor/src/processor/operations/io_ops.rs
  processor/src/processor/operations/mod.rs
  processor/src/processor/operations/stack_ops.rs
  processor/src/processor/operations/sys_ops.rs
  processor/src/processor/operations/u32_ops.rs
Labels: processor

#2185 fix: complete rename Span -> Basic Block
  docs/src/design/decoder/constraints.md
  docs/src/design/decoder/main.md
  docs/src/design/programs.md
  processor/src/decoder/block_stack.rs
  processor/src/decoder/mod.rs
  processor/src/decoder/trace.rs
  processor/src/fast/basic_block.rs
  processor/src/fast/execution_tracer.rs
  processor/src/fast/trace_state.rs
  processor/src/lib.rs
Labels: no changelog

#2194 sorted_array::push_lowerbound_result refactor
  processor/src/lib.rs
  processor/src/operations/sys_ops/sys_event_handlers.rs
  stdlib/src/handlers/sorted_array.rs
Labels: no changelog

#2120 feat(assembly): implement type signature syntax
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  assembly-syntax/src/ast/attribute/meta.rs
  assembly-syntax/src/ast/attribute/meta/expr.rs
  assembly-syntax/src/ast/constants.rs
  assembly-syntax/src/ast/imports.rs
  assembly-syntax/src/ast/instruction/mod.rs
  assembly-syntax/src/ast/instruction/print.rs
  assembly-syntax/src/ast/module.rs
  assembly-syntax/src/ast/procedure/alias.rs
  assembly-syntax/src/ast/procedure/mod.rs
  assembly-syntax/src/ast/procedure/procedure.rs
  assembly-syntax/src/ast/tests.rs
  assembly-syntax/src/ast/type.rs
  assembly-syntax/src/ast/visit.rs
  assembly-syntax/src/lib.rs
  assembly-syntax/src/library/mod.rs
  assembly-syntax/src/parser/error.rs
  assembly-syntax/src/parser/grammar.lalrpop
  assembly-syntax/src/parser/lexer.rs
  assembly-syntax/src/parser/mod.rs
  assembly-syntax/src/parser/token.rs
  assembly-syntax/src/sema/context.rs
  assembly-syntax/src/sema/errors.rs
  assembly-syntax/src/sema/mod.rs
  assembly-syntax/src/sema/passes/const_eval.rs
  assembly/src/assembler.rs
  assembly/src/instruction/env_ops.rs
  assembly/src/instruction/mod.rs
  assembly/src/instruction/procedures.rs
  assembly/src/linker/errors.rs
  assembly/src/linker/mod.rs
  assembly/src/procedure.rs
  assembly/src/tests.rs
Labels: assembly

#2198 ci: be specific about which toolchain to install & use
  .github/workflows/bench.yml
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: no changelog

#2201 Fix misleading expect message in range aux trace builder
  processor/src/range/aux_trace.rs
Labels: no changelog

#2217 Fix EXT2 ops docs
  air/src/constraints/stack/field_ops/mod.rs
  core/src/operations/mod.rs
  docs/src/user_docs/assembly/field_operations.md
  docs/src/user_docs/assembly/instruction_reference.md
Labels: no changelog

#2229 doc: escape brackets in rustdoc
  air/src/constraints/stack/field_ops/mod.rs
  core/src/operations/mod.rs
Labels: no changelog

#2230 chore: fix link checker job
  .github/workflows/link-checker.yml
  lychee.toml
Labels: no changelog
