Repository 0xMiden/miden-vm, pull requests merged in 2025-02, with the labels that each got.

#1653 chore(doc): rename `addr` field in kernel ROM to `idx`
  air/src/trace/main_trace.rs
  docs/src/assets/design/chiplets/kernel_rom/kernel_rom_execution_trace.png
  docs/src/design/chiplets/kernel_rom.md
  processor/src/chiplets/aux_trace/mod.rs
Labels: no changelog

#1645 docs: add documentation for FriE2F4 operation
  core/src/operations/mod.rs
Labels: no changelog

#1659 Fix overview.md document
  docs/src/intro/overview.md
Labels: documentation, no changelog

#1643 Assembler: enable vendoring of compiled libraries (fixes #1435)
  CHANGELOG.md
  assembly/src/assembler/mast_forest_builder.rs
  assembly/src/assembler/mod.rs
  assembly/src/assembler/module_graph/mod.rs
  assembly/src/tests.rs
  core/src/mast/mod.rs
  core/src/mast/node/call_node.rs
  core/src/mast/node/join_node.rs
  core/src/mast/node/loop_node.rs
  core/src/mast/node/mod.rs
  core/src/mast/node/split_node.rs
  miden/src/cli/run.rs
  miden/tests/integration/cli/cli_test.rs
  miden/tests/integration/cli/data/main.masm
Labels: assembly
