Repository 0xMiden/miden-vm, pull requests merged in 2025-04, with the labels that each got.

#1717 Helpful error messages for the processor (memory and calls)
  CHANGELOG.md
  Cargo.lock
  air/src/trace/main_trace.rs
  assembly/src/assembler/basic_block_builder.rs
  assembly/src/assembler/instruction/mod.rs
  assembly/src/assembler/mast_forest_builder.rs
  assembly/src/assembler/mod.rs
  assembly/src/testing.rs
  assembly/src/tests.rs
  core/src/debuginfo/source_manager.rs
  core/src/mast/merger/mod.rs
  core/src/mast/merger/tests.rs
  core/src/mast/mod.rs
  core/src/mast/node/basic_block_node/mod.rs
  core/src/mast/node/call_node.rs
  core/src/mast/node/dyn_node.rs
  core/src/mast/node/external.rs
  core/src/mast/node/join_node.rs
  core/src/mast/node/loop_node.rs
  core/src/mast/node/mod.rs
  core/src/mast/node/split_node.rs
  core/src/mast/serialization/mod.rs
  core/src/mast/serialization/tests.rs
  core/src/operations/decorators/mod.rs
  miden/benches/program_execution.rs
  miden/src/cli/data.rs
  miden/src/cli/debug/executor.rs
  miden/src/cli/debug/mod.rs
  miden/src/cli/prove.rs
  miden/src/cli/run.rs
  miden/src/cli/utils.rs
  miden/src/repl/mod.rs
  miden/src/tools/mod.rs
  miden/tests/integration/exec.rs
  miden/tests/integration/flow_control/mod.rs
  miden/tests/integration/operations/decorators/events.rs
  processor/Cargo.toml
  processor/src/chiplets/aux_trace/mod.rs
  processor/src/chiplets/memory/errors.rs
  processor/src/chiplets/memory/mod.rs
  processor/src/chiplets/memory/segment.rs
  processor/src/chiplets/memory/tests.rs
  processor/src/chiplets/mod.rs
  processor/src/decoder/aux_trace/mod.rs
  processor/src/decoder/mod.rs
  processor/src/errors.rs
  processor/src/lib.rs
  processor/src/operations/horner_ops.rs
  processor/src/operations/io_ops.rs
  processor/src/operations/mod.rs
  processor/src/operations/sys_ops/sys_event_handlers.rs
  processor/src/range/aux_trace.rs
  processor/src/stack/aux_trace.rs
  processor/src/tests.rs
  processor/src/trace/mod.rs
  prover/src/lib.rs
  stdlib/tests/crypto/falcon.rs
  stdlib/tests/crypto/stark/mod.rs
  test-utils/src/lib.rs
Labels: processor, debugging

#1735 fix: relax identifier rules
  CHANGELOG.md
  assembly/src/ast/attribute/meta.rs
  assembly/src/ast/attribute/meta/expr.rs
  assembly/src/ast/ident.rs
  assembly/src/ast/immediate.rs
  assembly/src/ast/procedure/name.rs
  assembly/src/ast/tests.rs
  assembly/src/library/namespace.rs
  assembly/src/library/path.rs
  assembly/src/parser/error.rs
  assembly/src/parser/grammar.lalrpop
  assembly/src/parser/lexer.rs
  miden/tests/integration/cli/cli_test.rs
Labels: assembly

#1755 Optimize build times
  .github/workflows/test.yml
  Cargo.toml
  Makefile
  miden/README.md
Labels: no changelog

#1756 Fix `assert_diagnostic_lines!`
  assembly/src/ast/tests.rs
  assembly/src/testing.rs
  assembly/src/tests.rs
Labels: no changelog

#1761 `ExecutionOptions::with_debugging()` now takes a boolean parameter
  .config/nextest.toml
  CHANGELOG.md
  Makefile
  air/src/options.rs
  miden/tests/integration/operations/decorators/events.rs
  processor/src/lib.rs
  stdlib/tests/main.rs
  test-utils/src/lib.rs
  test-utils/src/test_builders.rs
Labels: no changelog, debugging

#1767 Fix build
  processor/Cargo.toml
Labels: no changelog

#1773 Fix clippy
  air/src/trace/rows.rs
  assembly/src/ast/instruction/print.rs
  assembly/src/ast/invocation_target.rs
  assembly/src/ast/procedure/alias.rs
  assembly/src/sema/context.rs
  assembly/src/testing.rs
  core/src/mast/mod.rs
  core/src/mast/serialization/info.rs
  core/src/operations/decorators/mod.rs
  core/src/stack/inputs.rs
  core/src/stack/outputs.rs
  miden/benches/program_execution.rs
  miden/src/cli/bundle.rs
  miden/src/cli/data.rs
  miden/src/cli/debug/command.rs
  miden/src/cli/debug/executor.rs
  miden/src/cli/debug/mod.rs
  miden/src/cli/prove.rs
  miden/src/repl/mod.rs
  miden/src/tools/mod.rs
  package/src/package/mod.rs
  stdlib/tests/collections/mmr.rs
  stdlib/tests/mem/mod.rs
  test-utils/src/lib.rs
Labels: no changelog
